---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Get server name
      set_fact:
        server_name: "{{ ansible_hostname }}"

    - name: Check disk usage
      shell: df -hP / | awk 'NR==2{print $5}' | cut -d'%' -f1
      register: disk_usage
      changed_when: false

    - name: Send Discord notification if disk usage is high
      when: disk_usage.stdout|int >= 80
      uri:
        url: https://discord.com/api/webhooks/1090628082051842089/qCjPNPOJJnfpaby1hLmZAnpSz19JvpsglHCOUPKBngvh6Pcpeg_v-qx10oqNlgKhdlAe
        method: POST
        body_format: json
        body: '{"content": "Server {{ server_name }} - disk usage is at {{ disk_usage.stdout }}%"}'
      delegate_to: localhost
