---
- name: Update Raspberry Pi OS
  hosts: All
  become: true

  tasks:
    - name: Release apt lock
      block:
        - name: Remove apt lock file
          file:
            path: /var/lib/apt/lists/lock
            state: absent
            force: yes
          become: true
        - name: Remove apt lock directory
          file:
            path: /var/lib/apt/lists
            state: directory
            recurse: yes
            force: yes
          become: true
      ignore_errors: yes

    - name: Update package lists
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes

    - name: Upgrade distribution packages
      apt:
        upgrade_dist: yes

    - name: Clean up unnecessary packages
      apt:
        autoremove: yes

    - name: Reboot if required
      command: "reboot"
      async: 0
      poll: 0
      ignore_errors: true
