---
- name: Update Raspberry Pi OS
  hosts: all
  become: true

  tasks:
    - name: Release apt lock
      file:
        path: /var/lib/apt/lists/lock
        state: absent
      become: true

    - name: Update package lists
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes

    - name: Upgrade distribution packages
      apt:
        upgrade_dist: yes

    - name: Clean up unnecessary packages
      apt:
        autoremove: yes

    - name: Reboot if required
      command: "reboot"
      async: 0
      poll: 0
      ignore_errors: true
